---
deployment:
  tasks:
    - export DEPLOYPATH=/home/easytskc/public_html
    - /bin/cp -R public/. $DEPLOYPATH/
    - /bin/sed -i 's|/../vendor/|/../EasyTSK-v2/vendor/|g' $DEPLOYPATH/index.php
    - /bin/sed -i 's|/../bootstrap/|/../EasyTSK-v2/bootstrap/|g' $DEPLOYPATH/index.php
    - /bin/sed -i 's|/../storage/|/../EasyTSK-v2/storage/|g' $DEPLOYPATH/index.php
